server:
  port: 5555
# Token for discord bot
discord:
  token:
spring:
  profiles:
#   This can be changed to prod later
    active: dev
# DB info
  datasource:
    url:
    username:
    password:
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate
    open-in-view: false
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            idleWaitTime: 7500
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
springdoc:
  swagger-ui:
    use-root-path: true
management:
  endpoints:
    web:
      exposure:
        include: loggers
  endpoint:
    loggers:
      enabled: true